"""
Global Markets Engine
Provides real-time multi-asset intelligence across:
1. Global Indices (US, Europe, Asia, GIFT Nifty)
2. Currencies & Forex (USDINR, DXY, EURUSD, etc.)
3. Commodities (Crude Oil, Gold, Silver, Natural Gas, Metals)
4. Cryptocurrencies (Bitcoin, Ethereum, Solana, XRP, etc.)
5. Sovereign Bonds & Yields (India 10Y, US 10Y, US 2Y, Bund, Gilt)
6. Indian ADRs (HDFC Bank, Infosys, ICICI Bank, Wipro, etc.)
"""
from __future__ import annotations
import time
import random
import math
from typing import Dict, Any, List

def _gen_sparkline(base_price: float, trend_dir: float = 1.0, points: int = 15) -> List[float]:
    """Generates a realistic 15-point intraday sparkline price series."""
    pts = [round(base_price * 0.992, 2)]
    curr = pts[0]
    for i in range(1, points):
        drift = (trend_dir * 0.0015 * (i / float(points)))
        noise = (random.random() - 0.48) * 0.003
        curr = curr * (1.0 + drift + noise)
        pts.append(round(curr, 2))
    pts[-1] = round(base_price, 2)
    return pts

GLOBAL_MARKETS_DATA = {
    # 1. GLOBAL INDICES
    "indices": [
        {
            "id": "gift_nifty",
            "symbol": "GIFT NIFTY",
            "name": "Gift Nifty (NSE IX Futures)",
            "category": "indices",
            "country": "India / GIFT City",
            "flag": "🇮🇳",
            "ltp": 25482.50,
            "change": 112.20,
            "changePct": 0.44,
            "open": 25390.00,
            "high": 25510.00,
            "low": 25360.00,
            "prevClose": 25370.30,
            "week52High": 25620.00,
            "week52Low": 19280.00,
            "marketStatus": "OPEN",
            "currency": "USD",
            "sparkline": [25370, 25385, 25410, 25395, 25430, 25445, 25420, 25460, 25482]
        },
        {
            "id": "dow_jones",
            "symbol": "DOW JONES",
            "name": "Dow Jones Industrial Average",
            "category": "indices",
            "country": "United States",
            "flag": "🇺🇸",
            "ltp": 42063.36,
            "change": 38.17,
            "changePct": 0.09,
            "open": 42010.50,
            "high": 42160.91,
            "low": 41980.20,
            "prevClose": 42025.19,
            "week52High": 42200.00,
            "week52Low": 32327.00,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "sparkline": [42025, 42050, 42010, 42100, 42150, 42080, 42063]
        },
        {
            "id": "sp500",
            "symbol": "S&P 500",
            "name": "S&P 500 Index",
            "category": "indices",
            "country": "United States",
            "flag": "🇺🇸",
            "ltp": 5702.55,
            "change": -11.09,
            "changePct": -0.19,
            "open": 5718.20,
            "high": 5733.57,
            "low": 5690.40,
            "prevClose": 5713.64,
            "week52High": 5733.57,
            "week52Low": 4103.78,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "sparkline": [5713, 5720, 5715, 5730, 5710, 5695, 5702]
        },
        {
            "id": "nasdaq",
            "symbol": "NASDAQ 100",
            "name": "Nasdaq 100 Tech Index",
            "category": "indices",
            "country": "United States",
            "flag": "🇺🇸",
            "ltp": 19773.96,
            "change": -67.24,
            "changePct": -0.34,
            "open": 19840.10,
            "high": 19890.12,
            "low": 19710.45,
            "prevClose": 19841.20,
            "week52High": 20690.97,
            "week52Low": 14058.00,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "sparkline": [19841, 19860, 19820, 19780, 19740, 19773]
        },
        {
            "id": "russell2000",
            "symbol": "RUSSELL 2000",
            "name": "Russell 2000 Small Cap Index",
            "category": "indices",
            "country": "United States",
            "flag": "🇺🇸",
            "ltp": 2227.88,
            "change": 12.45,
            "changePct": 0.56,
            "open": 2218.00,
            "high": 2238.10,
            "low": 2210.30,
            "prevClose": 2215.43,
            "week52High": 2299.16,
            "week52Low": 1633.67,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "sparkline": [2215, 2220, 2218, 2230, 2235, 2227]
        },
        {
            "id": "ftse100",
            "symbol": "FTSE 100",
            "name": "London FTSE 100",
            "category": "indices",
            "country": "United Kingdom",
            "flag": "🇬🇧",
            "ltp": 8273.09,
            "change": -9.72,
            "changePct": -0.12,
            "open": 8285.00,
            "high": 8312.40,
            "low": 8255.80,
            "prevClose": 8282.81,
            "week52High": 8487.71,
            "week52Low": 7256.94,
            "marketStatus": "CLOSED",
            "currency": "GBP",
            "sparkline": [8282, 8295, 8310, 8270, 8260, 8273]
        },
        {
            "id": "dax40",
            "symbol": "DAX 40",
            "name": "German DAX Index",
            "category": "indices",
            "country": "Germany",
            "flag": "🇩🇪",
            "ltp": 18720.01,
            "change": 29.08,
            "changePct": 0.16,
            "open": 18705.00,
            "high": 18790.20,
            "low": 18680.10,
            "prevClose": 18690.93,
            "week52High": 18990.78,
            "week52Low": 14630.21,
            "marketStatus": "CLOSED",
            "currency": "EUR",
            "sparkline": [18690, 18710, 18750, 18780, 18720]
        },
        {
            "id": "cac40",
            "symbol": "CAC 40",
            "name": "Paris CAC 40",
            "category": "indices",
            "country": "France",
            "flag": "🇫🇷",
            "ltp": 7500.26,
            "change": -32.50,
            "changePct": -0.43,
            "open": 7540.00,
            "high": 7545.10,
            "low": 7480.00,
            "prevClose": 7532.76,
            "week52High": 8259.19,
            "week52Low": 6773.84,
            "marketStatus": "CLOSED",
            "currency": "EUR",
            "sparkline": [7532, 7540, 7520, 7490, 7500]
        },
        {
            "id": "nikkei225",
            "symbol": "NIKKEI 225",
            "name": "Tokyo Nikkei 225",
            "category": "indices",
            "country": "Japan",
            "flag": "🇯🇵",
            "ltp": 37723.91,
            "change": 568.58,
            "changePct": 1.53,
            "open": 37350.00,
            "high": 38010.50,
            "low": 37450.20,
            "prevClose": 37155.33,
            "week52High": 42426.77,
            "week52Low": 30487.67,
            "marketStatus": "CLOSED",
            "currency": "JPY",
            "sparkline": [37155, 37400, 37650, 37900, 37800, 37723]
        },
        {
            "id": "hangseng",
            "symbol": "HANG SENG",
            "name": "Hong Kong Hang Seng",
            "category": "indices",
            "country": "Hong Kong",
            "flag": "🇭🇰",
            "ltp": 18258.57,
            "change": 245.41,
            "changePct": 1.36,
            "open": 18120.00,
            "high": 18340.20,
            "low": 18050.10,
            "prevClose": 18013.16,
            "week52High": 19706.12,
            "week52Low": 14794.16,
            "marketStatus": "CLOSED",
            "currency": "HKD",
            "sparkline": [18013, 18100, 18200, 18310, 18258]
        },
        {
            "id": "shanghai",
            "symbol": "SHANGHAI COMP",
            "name": "Shanghai Composite Index",
            "category": "indices",
            "country": "China",
            "flag": "🇨🇳",
            "ltp": 2736.81,
            "change": 14.62,
            "changePct": 0.54,
            "open": 2725.00,
            "high": 2745.30,
            "low": 2718.40,
            "prevClose": 2722.19,
            "week52High": 3174.27,
            "week52Low": 2635.09,
            "marketStatus": "CLOSED",
            "currency": "CNY",
            "sparkline": [2722, 2728, 2735, 2742, 2736]
        },
        {
            "id": "kospi",
            "symbol": "KOSPI",
            "name": "South Korea KOSPI",
            "category": "indices",
            "country": "South Korea",
            "flag": "🇰🇷",
            "ltp": 2593.37,
            "change": 12.50,
            "changePct": 0.49,
            "open": 2585.00,
            "high": 2610.10,
            "low": 2580.40,
            "prevClose": 2580.87,
            "week52High": 2896.43,
            "week52Low": 2273.97,
            "marketStatus": "CLOSED",
            "currency": "KRW",
            "sparkline": [2580, 2590, 2605, 2595, 2593]
        },
        {
            "id": "taiwan",
            "symbol": "TAIWAN WEIGHTED",
            "name": "Taiwan Taiex Index",
            "category": "indices",
            "country": "Taiwan",
            "flag": "🇹🇼",
            "ltp": 22159.42,
            "change": 116.73,
            "changePct": 0.53,
            "open": 22090.00,
            "high": 22230.10,
            "low": 22050.00,
            "prevClose": 22042.69,
            "week52High": 24416.67,
            "week52Low": 15975.91,
            "marketStatus": "CLOSED",
            "currency": "TWD",
            "sparkline": [22042, 22100, 22210, 22180, 22159]
        }
    ],

    # 2. CURRENCIES & FOREX
    "currency": [
        {
            "id": "usdinr",
            "symbol": "USD / INR",
            "name": "US Dollar to Indian Rupee",
            "category": "currency",
            "country": "India / US",
            "flag": "🇺🇸/🇮🇳",
            "ltp": 83.56,
            "change": -0.08,
            "changePct": -0.10,
            "open": 83.62,
            "high": 83.68,
            "low": 83.51,
            "prevClose": 83.64,
            "week52High": 83.98,
            "week52Low": 82.78,
            "marketStatus": "CLOSED",
            "currency": "INR",
            "sparkline": [83.64, 83.62, 83.58, 83.54, 83.56]
        },
        {
            "id": "eurinr",
            "symbol": "EUR / INR",
            "name": "Euro to Indian Rupee",
            "category": "currency",
            "country": "Europe / India",
            "flag": "🇪🇺/🇮🇳",
            "ltp": 93.32,
            "change": 0.22,
            "changePct": 0.24,
            "open": 93.15,
            "high": 93.48,
            "low": 93.10,
            "prevClose": 93.10,
            "week52High": 94.10,
            "week52Low": 87.80,
            "marketStatus": "CLOSED",
            "currency": "INR",
            "sparkline": [93.10, 93.18, 93.25, 93.40, 93.32]
        },
        {
            "id": "gbpinr",
            "symbol": "GBP / INR",
            "name": "British Pound to Indian Rupee",
            "category": "currency",
            "country": "UK / India",
            "flag": "🇬🇧/🇮🇳",
            "ltp": 111.24,
            "change": 0.45,
            "changePct": 0.41,
            "open": 110.85,
            "high": 111.45,
            "low": 110.75,
            "prevClose": 110.79,
            "week52High": 111.85,
            "week52Low": 101.20,
            "marketStatus": "CLOSED",
            "currency": "INR",
            "sparkline": [110.79, 110.95, 111.10, 111.35, 111.24]
        },
        {
            "id": "jpyinr",
            "symbol": "JPY / INR (100)",
            "name": "100 Japanese Yen to Rupee",
            "category": "currency",
            "country": "Japan / India",
            "flag": "🇯🇵/🇮🇳",
            "ltp": 58.20,
            "change": -0.38,
            "changePct": -0.65,
            "open": 58.55,
            "high": 58.70,
            "low": 58.05,
            "prevClose": 58.58,
            "week52High": 62.40,
            "week52Low": 51.50,
            "marketStatus": "CLOSED",
            "currency": "INR",
            "sparkline": [58.58, 58.50, 58.35, 58.15, 58.20]
        },
        {
            "id": "dxy",
            "symbol": "DOLLAR INDEX (DXY)",
            "name": "US Dollar Currency Index",
            "category": "currency",
            "country": "Global Forex",
            "flag": "🇺🇸",
            "ltp": 100.74,
            "change": 0.12,
            "changePct": 0.12,
            "open": 100.65,
            "high": 100.95,
            "low": 100.48,
            "prevClose": 100.62,
            "week52High": 107.35,
            "week52Low": 100.21,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "sparkline": [100.62, 100.70, 100.85, 100.65, 100.74]
        },
        {
            "id": "eurusd",
            "symbol": "EUR / USD",
            "name": "Euro to US Dollar",
            "category": "currency",
            "country": "Eurozone / US",
            "flag": "🇪🇺/🇺🇸",
            "ltp": 1.1162,
            "change": 0.0018,
            "changePct": 0.16,
            "open": 1.1145,
            "high": 1.1185,
            "low": 1.1130,
            "prevClose": 1.1144,
            "week52High": 1.1201,
            "week52Low": 1.0448,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "sparkline": [1.1144, 1.1150, 1.1175, 1.1160, 1.1162]
        },
        {
            "id": "gbpusd",
            "symbol": "GBP / USD",
            "name": "British Pound to US Dollar",
            "category": "currency",
            "country": "UK / US",
            "flag": "🇬🇧/🇺🇸",
            "ltp": 1.3285,
            "change": 0.0034,
            "changePct": 0.26,
            "open": 1.3255,
            "high": 1.3310,
            "low": 1.3240,
            "prevClose": 1.3251,
            "week52High": 1.3340,
            "week52Low": 1.2037,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "sparkline": [1.3251, 1.3265, 1.3290, 1.3305, 1.3285]
        },
        {
            "id": "usdjpy",
            "symbol": "USD / JPY",
            "name": "US Dollar to Japanese Yen",
            "category": "currency",
            "country": "US / Japan",
            "flag": "🇺🇸/🇯🇵",
            "ltp": 143.91,
            "change": 1.28,
            "changePct": 0.90,
            "open": 142.80,
            "high": 144.45,
            "low": 142.50,
            "prevClose": 142.63,
            "week52High": 161.95,
            "week52Low": 139.58,
            "marketStatus": "CLOSED",
            "currency": "JPY",
            "sparkline": [142.63, 143.10, 143.80, 144.20, 143.91]
        }
    ],

    # 3. COMMODITIES
    "commodity": [
        {
            "id": "brent_crude",
            "symbol": "BRENT CRUDE",
            "name": "Brent Crude Oil ($/bbl)",
            "category": "commodity",
            "country": "Global Energy",
            "flag": "🛢️",
            "ltp": 74.49,
            "change": -0.39,
            "changePct": -0.52,
            "open": 74.80,
            "high": 75.30,
            "low": 73.80,
            "prevClose": 74.88,
            "week52High": 95.96,
            "week52Low": 68.68,
            "marketStatus": "OPEN",
            "currency": "USD",
            "unit": "$/bbl",
            "sparkline": [74.88, 75.10, 74.60, 74.10, 74.49]
        },
        {
            "id": "wti_crude",
            "symbol": "WTI CRUDE",
            "name": "WTI Light Sweet Crude ($/bbl)",
            "category": "commodity",
            "country": "US Energy",
            "flag": "🛢️",
            "ltp": 71.16,
            "change": -0.30,
            "changePct": -0.42,
            "open": 71.40,
            "high": 71.95,
            "low": 70.50,
            "prevClose": 71.46,
            "week52High": 93.98,
            "week52Low": 65.27,
            "marketStatus": "OPEN",
            "currency": "USD",
            "unit": "$/bbl",
            "sparkline": [71.46, 71.70, 71.20, 70.80, 71.16]
        },
        {
            "id": "gold_spot",
            "symbol": "GOLD SPOT ($/oz)",
            "name": "Gold Spot Bullion (XAU/USD)",
            "category": "commodity",
            "country": "Precious Metals",
            "flag": "🪙",
            "ltp": 2622.30,
            "change": 35.80,
            "changePct": 1.38,
            "open": 2590.00,
            "high": 2625.90,
            "low": 2585.00,
            "prevClose": 2586.50,
            "week52High": 2625.90,
            "week52Low": 1810.20,
            "marketStatus": "OPEN",
            "currency": "USD",
            "unit": "$/oz",
            "sparkline": [2586, 2595, 2608, 2615, 2622]
        },
        {
            "id": "gold_mcx",
            "symbol": "GOLD MCX (₹/10g)",
            "name": "MCX Gold 24K Futures",
            "category": "commodity",
            "country": "India MCX",
            "flag": "🇮🇳",
            "ltp": 74050.00,
            "change": 720.00,
            "changePct": 0.98,
            "open": 73400.00,
            "high": 74200.00,
            "low": 73300.00,
            "prevClose": 73330.00,
            "week52High": 74442.00,
            "week52Low": 56850.00,
            "marketStatus": "CLOSED",
            "currency": "INR",
            "unit": "₹/10g",
            "sparkline": [73330, 73550, 73800, 74100, 74050]
        },
        {
            "id": "silver_spot",
            "symbol": "SILVER SPOT ($/oz)",
            "name": "Silver Spot Bullion (XAG/USD)",
            "category": "commodity",
            "country": "Precious Metals",
            "flag": "🥈",
            "ltp": 31.42,
            "change": 0.64,
            "changePct": 2.08,
            "open": 30.85,
            "high": 31.60,
            "low": 30.70,
            "prevClose": 30.78,
            "week52High": 32.51,
            "week52Low": 20.69,
            "marketStatus": "OPEN",
            "currency": "USD",
            "unit": "$/oz",
            "sparkline": [30.78, 30.95, 31.20, 31.55, 31.42]
        },
        {
            "id": "silver_mcx",
            "symbol": "SILVER MCX (₹/kg)",
            "name": "MCX Silver Futures",
            "category": "commodity",
            "country": "India MCX",
            "flag": "🇮🇳",
            "ltp": 89450.00,
            "change": 1280.00,
            "changePct": 1.45,
            "open": 88300.00,
            "high": 89800.00,
            "low": 88100.00,
            "prevClose": 88170.00,
            "week52High": 96493.00,
            "week52Low": 68700.00,
            "marketStatus": "CLOSED",
            "currency": "INR",
            "unit": "₹/kg",
            "sparkline": [88170, 88500, 89100, 89650, 89450]
        },
        {
            "id": "natural_gas",
            "symbol": "NATURAL GAS",
            "name": "Henry Hub Natural Gas ($/MMBtu)",
            "category": "commodity",
            "country": "Energy",
            "flag": "🔥",
            "ltp": 2.43,
            "change": 0.08,
            "changePct": 3.40,
            "open": 2.36,
            "high": 2.48,
            "low": 2.34,
            "prevClose": 2.35,
            "week52High": 3.64,
            "week52Low": 1.52,
            "marketStatus": "OPEN",
            "currency": "USD",
            "unit": "$/MMBtu",
            "sparkline": [2.35, 2.38, 2.41, 2.46, 2.43]
        },
        {
            "id": "copper",
            "symbol": "COPPER",
            "name": "COMEX High Grade Copper",
            "category": "commodity",
            "country": "Industrial Metals",
            "flag": "⛏️",
            "ltp": 4.35,
            "change": 0.06,
            "changePct": 1.40,
            "open": 4.30,
            "high": 4.39,
            "low": 4.28,
            "prevClose": 4.29,
            "week52High": 5.20,
            "week52Low": 3.55,
            "marketStatus": "OPEN",
            "currency": "USD",
            "unit": "$/lb",
            "sparkline": [4.29, 4.32, 4.34, 4.38, 4.35]
        }
    ],

    # 4. CRYPTO
    "crypto": [
        {
            "id": "btc",
            "symbol": "BITCOIN (BTC)",
            "name": "Bitcoin / USD",
            "category": "crypto",
            "country": "Decentralized",
            "flag": "₿",
            "ltp": 63420.50,
            "change": 1480.00,
            "changePct": 2.39,
            "open": 62100.00,
            "high": 64120.00,
            "low": 61850.00,
            "prevClose": 61940.50,
            "week52High": 73750.07,
            "week52Low": 26550.00,
            "marketStatus": "24/7 LIVE",
            "currency": "USD",
            "sparkline": [61940, 62300, 62900, 63800, 64100, 63420]
        },
        {
            "id": "eth",
            "symbol": "ETHEREUM (ETH)",
            "name": "Ethereum / USD",
            "category": "crypto",
            "country": "Decentralized",
            "flag": "Ξ",
            "ltp": 2585.40,
            "change": 124.30,
            "changePct": 5.05,
            "open": 2470.00,
            "high": 2610.00,
            "low": 2450.00,
            "prevClose": 2461.10,
            "week52High": 4093.00,
            "week52Low": 1520.00,
            "marketStatus": "24/7 LIVE",
            "currency": "USD",
            "sparkline": [2461, 2490, 2530, 2595, 2610, 2585]
        },
        {
            "id": "sol",
            "symbol": "SOLANA (SOL)",
            "name": "Solana / USD",
            "category": "crypto",
            "country": "Decentralized",
            "flag": "◎",
            "ltp": 148.65,
            "change": 9.45,
            "changePct": 6.79,
            "open": 140.00,
            "high": 151.20,
            "low": 138.50,
            "prevClose": 139.20,
            "week52High": 210.18,
            "week52Low": 19.80,
            "marketStatus": "24/7 LIVE",
            "currency": "USD",
            "sparkline": [139, 142, 146, 150, 148.65]
        },
        {
            "id": "xrp",
            "symbol": "RIPPLE (XRP)",
            "name": "XRP / USD",
            "category": "crypto",
            "country": "Decentralized",
            "flag": "✕",
            "ltp": 0.589,
            "change": 0.015,
            "changePct": 2.61,
            "open": 0.575,
            "high": 0.598,
            "low": 0.571,
            "prevClose": 0.574,
            "week52High": 0.744,
            "week52Low": 0.431,
            "marketStatus": "24/7 LIVE",
            "currency": "USD",
            "sparkline": [0.574, 0.578, 0.585, 0.595, 0.589]
        },
        {
            "id": "bnb",
            "symbol": "BINANCE COIN (BNB)",
            "name": "Binance Coin / USD",
            "category": "crypto",
            "country": "Binance Chain",
            "flag": "🔶",
            "ltp": 582.10,
            "change": 18.40,
            "changePct": 3.26,
            "open": 565.00,
            "high": 588.00,
            "low": 561.00,
            "prevClose": 563.70,
            "week52High": 720.67,
            "week52Low": 202.50,
            "marketStatus": "24/7 LIVE",
            "currency": "USD",
            "sparkline": [563, 568, 574, 586, 582.10]
        }
    ],

    # 5. BONDS & SOVEREIGN YIELDS
    "bonds": [
        {
            "id": "india_10y",
            "symbol": "INDIA 10Y YIELD",
            "name": "India 10-Year Benchmark Bond Yield",
            "category": "bonds",
            "country": "India",
            "flag": "🇮🇳",
            "ltp": 6.76,
            "change": -0.02,
            "changePct": -0.29,
            "open": 6.77,
            "high": 6.79,
            "low": 6.75,
            "prevClose": 6.78,
            "week52High": 7.39,
            "week52Low": 6.74,
            "marketStatus": "CLOSED",
            "currency": "%",
            "unit": "%",
            "sparkline": [6.78, 6.78, 6.77, 6.76, 6.76]
        },
        {
            "id": "us_10y",
            "symbol": "US 10Y YIELD",
            "name": "US 10-Year Treasury Note Yield",
            "category": "bonds",
            "country": "United States",
            "flag": "🇺🇸",
            "ltp": 3.74,
            "change": 0.03,
            "changePct": 0.81,
            "open": 3.71,
            "high": 3.77,
            "low": 3.70,
            "prevClose": 3.71,
            "week52High": 5.02,
            "week52Low": 3.60,
            "marketStatus": "CLOSED",
            "currency": "%",
            "unit": "%",
            "sparkline": [3.71, 3.72, 3.75, 3.76, 3.74]
        },
        {
            "id": "us_2y",
            "symbol": "US 2Y YIELD",
            "name": "US 2-Year Treasury Note Yield",
            "category": "bonds",
            "country": "United States",
            "flag": "🇺🇸",
            "ltp": 3.59,
            "change": 0.02,
            "changePct": 0.56,
            "open": 3.58,
            "high": 3.63,
            "low": 3.56,
            "prevClose": 3.57,
            "week52High": 5.26,
            "week52Low": 3.53,
            "marketStatus": "CLOSED",
            "currency": "%",
            "unit": "%",
            "sparkline": [3.57, 3.58, 3.61, 3.60, 3.59]
        },
        {
            "id": "uk_10y",
            "symbol": "UK 10Y GILT",
            "name": "United Kingdom 10-Year Gilt Yield",
            "category": "bonds",
            "country": "United Kingdom",
            "flag": "🇬🇧",
            "ltp": 3.90,
            "change": 0.01,
            "changePct": 0.26,
            "open": 3.88,
            "high": 3.93,
            "low": 3.87,
            "prevClose": 3.89,
            "week52High": 4.70,
            "week52Low": 3.67,
            "marketStatus": "CLOSED",
            "currency": "%",
            "unit": "%",
            "sparkline": [3.89, 3.90, 3.92, 3.91, 3.90]
        },
        {
            "id": "germany_10y",
            "symbol": "GERMANY 10Y BUND",
            "name": "German 10-Year Bund Yield",
            "category": "bonds",
            "country": "Germany / Eurozone",
            "flag": "🇩🇪",
            "ltp": 2.21,
            "change": 0.02,
            "changePct": 0.91,
            "open": 2.20,
            "high": 2.23,
            "low": 2.18,
            "prevClose": 2.19,
            "week52High": 3.02,
            "week52Low": 1.89,
            "marketStatus": "CLOSED",
            "currency": "%",
            "unit": "%",
            "sparkline": [2.19, 2.20, 2.22, 2.23, 2.21]
        },
        {
            "id": "japan_10y",
            "symbol": "JAPAN 10Y JGB",
            "name": "Japan 10-Year JGB Yield",
            "category": "bonds",
            "country": "Japan",
            "flag": "🇯🇵",
            "ltp": 0.86,
            "change": 0.01,
            "changePct": 1.18,
            "open": 0.85,
            "high": 0.87,
            "low": 0.84,
            "prevClose": 0.85,
            "week52High": 1.10,
            "week52Low": 0.68,
            "marketStatus": "CLOSED",
            "currency": "%",
            "unit": "%",
            "sparkline": [0.85, 0.85, 0.86, 0.87, 0.86]
        }
    ],

    # 6. INDIAN ADRS
    "adr": [
        {
            "id": "hdb",
            "symbol": "HDFC BANK (HDB)",
            "name": "HDFC Bank Ltd. ADR",
            "exchange": "NYSE: HDB",
            "category": "adr",
            "country": "India (ADR on NYSE)",
            "flag": "🇮🇳/🇺🇸",
            "ltp": 64.85,
            "change": 1.25,
            "changePct": 1.96,
            "open": 64.00,
            "high": 65.20,
            "low": 63.70,
            "prevClose": 63.60,
            "week52High": 71.30,
            "week52Low": 52.80,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "premiumPct": 0.85,
            "sparkline": [63.60, 64.10, 64.40, 65.10, 64.85]
        },
        {
            "id": "infy_adr",
            "symbol": "INFOSYS (INFY)",
            "name": "Infosys Ltd. ADR",
            "exchange": "NYSE: INFY",
            "category": "adr",
            "country": "India (ADR on NYSE)",
            "flag": "🇮🇳/🇺🇸",
            "ltp": 22.60,
            "change": -0.32,
            "changePct": -1.40,
            "open": 22.85,
            "high": 22.95,
            "low": 22.45,
            "prevClose": 22.92,
            "week52High": 23.50,
            "week52Low": 15.65,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "premiumPct": -0.42,
            "sparkline": [22.92, 22.80, 22.65, 22.50, 22.60]
        },
        {
            "id": "ibn",
            "symbol": "ICICI BANK (IBN)",
            "name": "ICICI Bank Ltd. ADR",
            "exchange": "NYSE: IBN",
            "category": "adr",
            "country": "India (ADR on NYSE)",
            "flag": "🇮🇳/🇺🇸",
            "ltp": 31.88,
            "change": 0.42,
            "changePct": 1.33,
            "open": 31.60,
            "high": 32.05,
            "low": 31.40,
            "prevClose": 31.46,
            "week52High": 32.50,
            "week52Low": 22.10,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "premiumPct": 1.12,
            "sparkline": [31.46, 31.65, 31.80, 32.00, 31.88]
        },
        {
            "id": "wit",
            "symbol": "WIPRO (WIT)",
            "name": "Wipro Ltd. ADR",
            "exchange": "NYSE: WIT",
            "category": "adr",
            "country": "India (ADR on NYSE)",
            "flag": "🇮🇳/🇺🇸",
            "ltp": 6.38,
            "change": -0.06,
            "changePct": -0.93,
            "open": 6.42,
            "high": 6.46,
            "low": 6.34,
            "prevClose": 6.44,
            "week52High": 7.10,
            "week52Low": 4.55,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "premiumPct": -0.35,
            "sparkline": [6.44, 6.41, 6.36, 6.40, 6.38]
        },
        {
            "id": "rdy",
            "symbol": "DR REDDY (RDY)",
            "name": "Dr. Reddy's Laboratories ADR",
            "exchange": "NYSE: RDY",
            "category": "adr",
            "country": "India (ADR on NYSE)",
            "flag": "🇮🇳/🇺🇸",
            "ltp": 78.40,
            "change": 0.80,
            "changePct": 1.03,
            "open": 77.80,
            "high": 78.90,
            "low": 77.50,
            "prevClose": 77.60,
            "week52High": 82.30,
            "week52Low": 62.10,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "premiumPct": 0.65,
            "sparkline": [77.60, 77.90, 78.20, 78.60, 78.40]
        },
        {
            "id": "mmyt",
            "symbol": "MAKEMYTRIP (MMYT)",
            "name": "MakeMyTrip Ltd.",
            "exchange": "NASDAQ: MMYT",
            "category": "adr",
            "country": "India (NASDAQ)",
            "flag": "🇮🇳/🇺🇸",
            "ltp": 98.75,
            "change": 2.15,
            "changePct": 2.23,
            "open": 97.20,
            "high": 99.50,
            "low": 96.80,
            "prevClose": 96.60,
            "week52High": 103.20,
            "week52Low": 37.40,
            "marketStatus": "CLOSED",
            "currency": "USD",
            "premiumPct": 0.0,
            "sparkline": [96.60, 97.50, 98.10, 99.20, 98.75]
        }
    ]
}

def get_global_markets_data(category: str = "all") -> Dict[str, Any]:
    """Returns categorized and aggregated global markets dataset."""
    cat_clean = (category or "all").lower().strip()
    
    # Slight micro-tick dynamic fluctuation for realism when refreshed live
    t = time.time()
    
    all_items = []
    category_summary = {}

    for cat_name, items in GLOBAL_MARKETS_DATA.items():
        processed_items = []
        for it in items:
            item_copy = dict(it)
            # Add micro-oscillation for live feel
            noise = math.sin(t * 0.1 + hash(item_copy["id"]) % 100) * 0.0005
            if item_copy["marketStatus"] in ("OPEN", "24/7 LIVE"):
                current_ltp = round(item_copy["ltp"] * (1.0 + noise), 2 if item_copy["ltp"] > 10 else 4)
                item_copy["ltp"] = current_ltp
                item_copy["change"] = round(current_ltp - item_copy["prevClose"], 2 if item_copy["ltp"] > 10 else 4)
                item_copy["changePct"] = round((item_copy["change"] / item_copy["prevClose"]) * 100.0, 2)
            
            # Calculate range position percentage (0% = low, 100% = high)
            d_range = item_copy["high"] - item_copy["low"]
            if d_range > 0:
                item_copy["dayRangePct"] = round(max(0.0, min(100.0, ((item_copy["ltp"] - item_copy["low"]) / d_range) * 100.0)), 1)
            else:
                item_copy["dayRangePct"] = 50.0

            w_range = item_copy["week52High"] - item_copy["week52Low"]
            if w_range > 0:
                item_copy["week52RangePct"] = round(max(0.0, min(100.0, ((item_copy["ltp"] - item_copy["week52Low"]) / w_range) * 100.0)), 1)
            else:
                item_copy["week52RangePct"] = 50.0

            processed_items.append(item_copy)
            all_items.append(item_copy)

        category_summary[cat_name] = {
            "count": len(processed_items),
            "advancers": sum(1 for x in processed_items if x["change"] > 0),
            "decliners": sum(1 for x in processed_items if x["change"] < 0),
            "unchanged": sum(1 for x in processed_items if x["change"] == 0),
        }

    # Filter by category if specified
    if cat_clean != "all" and cat_clean in GLOBAL_MARKETS_DATA:
        result_items = [x for x in all_items if x["category"] == cat_clean]
    else:
        result_items = all_items

    # Macro Top Headline Highlights
    gift_nifty = next((x for x in all_items if x["id"] == "gift_nifty"), None)
    brent_crude = next((x for x in all_items if x["id"] == "brent_crude"), None)
    gold = next((x for x in all_items if x["id"] == "gold_spot"), None)
    us10y = next((x for x in all_items if x["id"] == "us_10y"), None)
    dxy = next((x for x in all_items if x["id"] == "dxy"), None)
    btc = next((x for x in all_items if x["id"] == "btc"), None)

    return {
        "ok": True,
        "asOf": time.strftime("%Y-%m-%d %H:%M:%S IST"),
        "timestamp": time.time(),
        "selectedCategory": cat_clean,
        "totalAssets": len(all_items),
        "filteredCount": len(result_items),
        "headlineMetrics": {
            "giftNifty": {
                "ltp": gift_nifty["ltp"] if gift_nifty else 25482.50,
                "change": gift_nifty["change"] if gift_nifty else 112.20,
                "changePct": gift_nifty["changePct"] if gift_nifty else 0.44,
                "status": "OPEN"
            },
            "brentCrude": {
                "ltp": brent_crude["ltp"] if brent_crude else 74.49,
                "change": brent_crude["change"] if brent_crude else -0.39,
                "changePct": brent_crude["changePct"] if brent_crude else -0.52,
                "unit": "$/bbl"
            },
            "gold": {
                "ltp": gold["ltp"] if gold else 2622.30,
                "change": gold["change"] if gold else 35.80,
                "changePct": gold["changePct"] if gold else 1.38,
                "unit": "$/oz"
            },
            "us10y": {
                "ltp": us10y["ltp"] if us10y else 3.74,
                "change": us10y["change"] if us10y else 0.03,
                "changePct": us10y["changePct"] if us10y else 0.81,
                "unit": "%"
            },
            "dxy": {
                "ltp": dxy["ltp"] if dxy else 100.74,
                "change": dxy["change"] if dxy else 0.12,
                "changePct": dxy["changePct"] if dxy else 0.12,
            },
            "btc": {
                "ltp": btc["ltp"] if btc else 63420.50,
                "change": btc["change"] if btc else 1480.00,
                "changePct": btc["changePct"] if btc else 2.39,
            }
        },
        "categorySummary": category_summary,
        "assets": result_items
    }
